package fr.stri.projetperudo;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. CHATS fjh:dshdjk
 */

/**
 *
 * @author Quizz
 */
public class JoueurInterface extends javax.swing.JFrame {
    
    Joueurs j;
    String nomP;

    
    
    public void actualiserDes(Joueurs j)
    {
         
	  
          
           for (int i = 0; i < j.getListeDes().size();i++)
            {
	      
                jTextAreaAffDes.append(String.valueOf(j.getListeDes().get(i)));
	             
	    }
	       
	       jTextAreaAffDes.append("////");
	       
                  
                  
                  
    }
    
    
    

    /**
     * Creates new form Joueur
     */
    public JoueurInterface(Joueurs j,String nomP) {
        
        this.j=j;
        this.nomP=nomP;
        initComponents();
        
        
        
            actualiserDes(j);
        
            //Déclaration du timer (pour actualisation toute les 1000 miliseconds)
        Timer tMessage = new Timer(1000, new ActionListener() {
       
        public void actionPerformed(ActionEvent e) {
            actualiserDes(j);
        }           
        });
        tMessage.start();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumDeSurenchere = new javax.swing.JComboBox<>();
        ValideSurenchere = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BoutonPile = new javax.swing.JButton();
        BoutonMenteur = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAffDes = new javax.swing.JTextArea();

        jLabel4.setText("Numéro du dé");

        jLabel5.setText("Nombre");

        NumDeSurenchere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        NumDeSurenchere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumDeSurenchereActionPerformed(evt);
            }
        });

        ValideSurenchere.setText("Validé");
        ValideSurenchere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValideSurenchereActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumDeSurenchere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(ValideSurenchere)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumDeSurenchere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(ValideSurenchere)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Joueur");

        jLabel2.setText("Mes dés");

        jLabel3.setText("Message :");

        BoutonPile.setText("Pile");
        BoutonPile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPileActionPerformed(evt);
            }
        });

        BoutonMenteur.setText("Menteur");
        BoutonMenteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMenteurActionPerformed(evt);
            }
        });

        jButton3.setText("Surenchérir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextAreaAffDes.setColumns(20);
        jTextAreaAffDes.setRows(5);
        jTextAreaAffDes.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextAreaAffDesInputMethodTextChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaAffDes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(411, 411, 411))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(BoutonPile)
                                .addGap(174, 174, 174)
                                .addComponent(BoutonMenteur)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonPile)
                    .addComponent(BoutonMenteur)
                    .addComponent(jButton3))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jFrame1.setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void NumDeSurenchereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumDeSurenchereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumDeSurenchereActionPerformed

    private void BoutonMenteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMenteurActionPerformed
        // TODO add your handling code here:
        
        
        
                 InterfaceServCli proxy = null;
        try {
            proxy = (InterfaceServCli) Naming.lookup("rmi://localhost:1099/MonServeur");
        } catch (NotBoundException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //String returncreerpartie = creerpartie.proxy.CreerPartie(resultnomPartie, resultnombreJoueurs);
            proxy.menteurRMI(j, nomP);
            //ProxyRMI();
            //JOptionPane.showMessageDialog(null, returncreerpartie);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }                   
        
  
        
        
    }//GEN-LAST:event_BoutonMenteurActionPerformed

    private void jTextAreaAffDesInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextAreaAffDesInputMethodTextChanged
    /*ConnexionJoueur recupnomj = new ConnexionJoueur();
    Joueurs j;   
    j = recupnomj.getEnvoijoueur();
        System.out.println(j.getListeDes());*/

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAffDesInputMethodTextChanged

    private void BoutonPileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPileActionPerformed
        // TODO add your handling code here:
        
        
         InterfaceServCli proxy = null;
        try {
            proxy = (InterfaceServCli) Naming.lookup("rmi://localhost:1099/MonServeur");
        } catch (NotBoundException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //String returncreerpartie = creerpartie.proxy.CreerPartie(resultnomPartie, resultnombreJoueurs);
            proxy.pilRMI(j, nomP);
            //ProxyRMI();
            //JOptionPane.showMessageDialog(null, returncreerpartie);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }                   
        
    }//GEN-LAST:event_BoutonPileActionPerformed

    private void ValideSurenchereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValideSurenchereActionPerformed
        
        Integer resultNumDes;
         Integer resultNbDes;
        Integer resultNumDes = NumDeSurenchere.getSelectedItem();
        Integer resultNbDes = jSpinner1.getValue();
        
        InterfaceServCli proxy = null;
        try {
            proxy = (InterfaceServCli) Naming.lookup("rmi://localhost:1099/MonServeur");
        } catch (NotBoundException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            //String returncreerpartie = creerpartie.proxy.CreerPartie(resultnomPartie, resultnombreJoueurs);
            proxy.surchargeRMI(j, resultNumDes, resultNbDes, nomP);
            //ProxyRMI();
            //JOptionPane.showMessageDialog(null, returncreerpartie);
        } catch (RemoteException ex) {
            Logger.getLogger(ConnexionJoueur.class.getName()).log(Level.SEVERE, null, ex);
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_ValideSurenchereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(Joueurs j, String nomP) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoueurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoueurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoueurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoueurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JoueurInterface(j,nomP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonMenteur;
    private javax.swing.JButton BoutonPile;
    private javax.swing.JComboBox<String> NumDeSurenchere;
    private javax.swing.JButton ValideSurenchere;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaAffDes;
    // End of variables declaration//GEN-END:variables
}
